"""inbox_pro

Revision ID: 8403a6539976
Revises: 20260621_0013
Create Date: 2026-06-24 19:10:23.015616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8403a6539976'
down_revision: Union[str, None] = '20260621_0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_replies_id'), 'saved_replies', ['id'], unique=False)
    op.create_index(op.f('ix_saved_replies_store_id'), 'saved_replies', ['store_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False)
    op.add_column('instagram_automation_events', sa.Column('assigned_to', sa.String(length=255), nullable=False))
    op.add_column('instagram_automation_events', sa.Column('internal_note', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'posts', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('instagram_automation_events', 'internal_note')
    op.drop_column('instagram_automation_events', 'assigned_to')
    op.drop_index(op.f('ix_instagram_accounts_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_saved_replies_store_id'), table_name='saved_replies')
    op.drop_index(op.f('ix_saved_replies_id'), table_name='saved_replies')
    op.drop_table('saved_replies')
    # ### end Alembic commands ###

